//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompEmpManageWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int EmpId { get; set; }
        public string IdentityNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CompId { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
